# Generated by Django 3.2.8 on 2021-11-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=80)),
                ('msg_status', models.CharField(max_length=20)),
                ('template', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'message',
                'managed': True,
            },
        ),
    ]
