# Generated by Django 4.2.5 on 2023-11-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0004_failedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
