# Generated by Django 5.0.2 on 2024-10-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0005_message_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email_service_msg_id_str',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='ophauthentication',
            name='viestinvalitys_session_cookie',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='ophauthentication',
            name='viestinvalitys_session_cookie_last_update_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
