# Generated by Django 4.2.18 on 2025-01-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0006_message_email_service_msg_id_str_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageQueue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=80)),
                ('vastaajatunnus', models.CharField(max_length=20)),
                ('message', models.CharField(default='', max_length=5000)),
                ('template', models.IntegerField()),
                ('msg_id', models.IntegerField()),
                ('pdfs_encoded', models.JSONField(default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messagequeue',
                'managed': True,
            },
        ),
    ]
