# Generated by Django 4.2.18 on 2025-02-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0007_messagequeue'),
    ]

    operations = [
        migrations.AddField(
            model_name='ophauthentication',
            name='tgt_last_cleared_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
