# Generated by Django 4.2.18 on 2025-04-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0008_ophauthentication_tgt_last_cleared_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email_service_status_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
