# Generated by Django 4.0.8 on 2022-10-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raportointi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oph_tgt', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'externalservices',
                'managed': True,
            },
        ),
    ]
