# Generated by Django 4.0.8 on 2022-11-24 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raportointi', '0002_externalservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kysymysryhmaid', models.IntegerField(unique=True)),
                ('title_fi', models.CharField(blank=True, max_length=200, null=True)),
                ('title_sv', models.CharField(blank=True, max_length=200, null=True)),
                ('description_fi', models.TextField(blank=True, null=True)),
                ('description_sv', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reportingtemplate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReportingTemplateHelptext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('title_fi', models.CharField(blank=True, max_length=200, null=True)),
                ('title_sv', models.CharField(blank=True, max_length=200, null=True)),
                ('description_fi', models.TextField(blank=True, null=True)),
                ('description_sv', models.TextField(blank=True, null=True)),
                ('reporting_template', models.ForeignKey(db_column='reportingtemplate', on_delete=django.db.models.deletion.DO_NOTHING, related_name='template_helptexts', to='raportointi.reportingtemplate')),
            ],
            options={
                'db_table': 'ReportingTemplateHelptext',
                'managed': True,
            },
        ),
    ]
