# Generated by Django 4.1.6 on 2023-02-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raportointi', '0003_reportingtemplate_reportingtemplatehelptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kyselykertaid', models.IntegerField()),
                ('oppilaitos', models.CharField(max_length=40)),
                ('kuvaus', models.CharField(blank=True, max_length=5000, null=True)),
                ('aineisto', models.CharField(blank=True, max_length=5000, null=True)),
                ('vahvuudet', models.CharField(blank=True, max_length=5000, null=True)),
                ('kohteet', models.CharField(blank=True, max_length=5000, null=True)),
                ('keh_toimenpiteet', models.CharField(blank=True, max_length=5000, null=True)),
                ('seur_toimenpiteet', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'summary',
                'managed': True,
                'unique_together': {('kyselykertaid', 'oppilaitos')},
            },
        ),
    ]
