# Generated by Django 4.1.6 on 2023-02-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raportointi', '0006_summary_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='group_info',
            field=models.CharField(default='', max_length=200),
        ),
    ]
