# Generated by Django 4.1.7 on 2023-02-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raportointi', '0009_alter_summary_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='koulutustoimija',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
