# Generated by Django 4.1.7 on 2023-07-26 07:50

from django.db import migrations, models

from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('raportointi', '0012_alter_result_aineisto_alter_result_keh_toimenpiteet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indikaattori',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('key', models.CharField(max_length=100, unique=True)),
                ('laatutekija', models.CharField(max_length=100)),
                ('is_visible', models.BooleanField()),
            ],
            options={
                'db_table': 'indikaattori',
                'managed': settings.TESTING,
            },
        ),
    ]
