# Generated by Django 4.2.17 on 2025-01-14 13:35

from django.db import migrations, models

from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('raportointi', '0013_indikaattori'),
    ]

    operations = [
        migrations.CreateModel(
            name='AluejakoAlue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('koulutustoimija', models.CharField(max_length=100)),
                ('name_fi', models.CharField(max_length=100)),
                ('name_sv', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'aluejakoalue',
                'managed': settings.TESTING,
            },
        ),
    ]
