# Generated by Django 4.2.17 on 2025-02-11 13:10

from django.db import migrations, models

from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('raportointi', '0014_aluejakoalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('locale', models.CharField(max_length=3)),
                ('value', models.CharField(max_length=5000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'localisation',
                'managed': settings.TESTING,
            },
        ),
    ]
