# Generated by Django 4.2.21 on 2025-06-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raportointi', '0015_localisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='is_skipped',
            field=models.BooleanField(default=False),
        ),
    ]
