# Generated by Django 5.2.6 on 2025-10-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raportointi", "0016_summary_is_skipped"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scale",
            name="label_fi",
        ),
        migrations.RemoveField(
            model_name="scale",
            name="label_sv",
        ),
        migrations.AddField(
            model_name="scale",
            name="label",
            field=models.JSONField(default=dict),
        ),
    ]
