# Generated by Django 3.2.10 on 2021-12-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tyontekija',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tyontekija_id', models.IntegerField()),
                ('kutsumanimi', models.CharField(max_length=50)),
                ('sukunimi', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80)),
                ('tehtavanimike', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tyontekija',
                'managed': True,
            },
        ),
    ]
