# Generated by Django 3.2.10 on 2022-01-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyontekija',
            name='kelpoisuus',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tyontekija',
            name='tutkinto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tyontekija',
            name='tehtavanimike',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
