# Generated by Django 3.2.10 on 2022-04-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0002_auto_20220110_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='OphAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgt', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'ophauthentication',
                'managed': True,
            },
        ),
    ]
