# Generated by Django 3.2.10 on 2022-05-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0004_auto_20220421_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='KyselySend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tyontekija_id', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=80)),
                ('kyselykerta', models.IntegerField()),
                ('vastaajatunnus', models.CharField(max_length=20)),
                ('msg_id', models.IntegerField()),
                ('msg_status', models.CharField(max_length=20)),
                ('message', models.CharField(default='', max_length=5000)),
            ],
            options={
                'db_table': 'kyselysend',
                'managed': True,
            },
        ),
    ]
