# Generated by Django 3.2.10 on 2022-05-18 11:04

from django.db import migrations

from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0005_kyselysend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kyselykysymysryhma',
            options={'managed': settings.TESTING, 'ordering': ['jarjestys']},
        ),
    ]
