# Generated by Django 3.2.10 on 2022-06-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0006_alter_kyselykysymysryhma_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indikaattori',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('key', models.CharField(max_length=100)),
                ('laatutekija', models.CharField(max_length=100)),
                ('is_visible', models.BooleanField()),
            ],
            options={
                'db_table': 'indikaattori',
                'managed': True,
            },
        ),
    ]
