# Generated by Django 4.0.5 on 2022-08-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0007_indikaattori'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyselysend',
            name='kutsumanimi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyselysend',
            name='sukunimi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyselysend',
            name='tehtavanimike',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
