# Generated by Django 4.0.5 on 2022-08-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0008_kyselysend_kutsumanimi_kyselysend_sukunimi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oph_tgt', models.CharField(blank=True, max_length=300)),
                ('varda_apikey', models.CharField(blank=True, max_length=100)),
                ('varda_organisaatiot_last_update_time', models.CharField(blank=True, max_length=50)),
                ('varda_toimipaikat_last_update_time', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'externalservices',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='OphAuthentication',
        ),
    ]
