# Generated by Django 4.0.5 on 2022-09-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0010_remove_kyselysend_tehtavanimike_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tyontekija',
        ),
    ]
