# Generated by Django 4.0.5 on 2022-09-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0012_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='scale',
            name='order_no',
            field=models.IntegerField(default=0),
        ),
    ]
