# Generated by Django 4.0.5 on 2022-09-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0013_scale_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indikaattori',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
