# Generated by Django 4.0.5 on 2022-11-03 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0014_alter_indikaattori_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Koodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koodisto_uri', models.CharField(max_length=256)),
                ('nimi_fi', models.CharField(blank=True, max_length=256, null=True)),
                ('nimi_sv', models.CharField(blank=True, max_length=256, null=True)),
                ('nimi_en', models.CharField(blank=True, max_length=256, null=True)),
                ('koodi_arvo', models.CharField(max_length=256)),
                ('voimassa_alkupvm', models.DateField(blank=True, null=True)),
                ('voimassa_loppupvm', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'koodi',
                'managed': settings.TESTING,
            },
        ),
    ]
