# Generated by Django 4.1.7 on 2023-05-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0016_scale_eos_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthorization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('oid', models.CharField(blank=True, max_length=40, null=True)),
                ('permissions', models.JSONField(default=dict)),
                ('updated_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'userauthorization',
                'managed': True,
            },
        ),
    ]
