# Generated by Django 4.1.7 on 2023-06-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0018_malfunctionmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='malfunctionmessage',
            name='service',
            field=models.CharField(default='virkailijapalvelu', max_length=50),
        ),
    ]
