# Generated by Django 4.2.11 on 2024-03-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0020_scale_eos_allowed_scale_is_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indikaattori',
            old_name='key',
            new_name='indicator_key',
        ),
    ]
