# Generated by Django 4.2.15 on 2024-12-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0021_rename_key_indikaattori_indicator_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AluejakoAlue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('koulutustoimija', models.CharField(max_length=100)),
                ('name_fi', models.CharField(max_length=100)),
                ('name_sv', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'aluejakoalue',
                'managed': True,
            },
        ),
    ]
