# Generated by Django 4.2.15 on 2025-02-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0022_aluejakoalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('locale', models.CharField(max_length=3)),
                ('value', models.CharField(max_length=5000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'localisation',
                'managed': True,
            },
        ),
    ]
