# Generated by Django 5.2.6 on 2025-10-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyselyt", "0023_localisation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scale",
            name="label_fi",
        ),
        migrations.RemoveField(
            model_name="scale",
            name="label_sv",
        ),
        migrations.AddField(
            model_name="scale",
            name="label",
            field=models.JSONField(default=dict),
        ),
    ]
