INDICATORS_SHORT_DICT = dict(
    myonteinen_ja_sitoutunut_vuorovaik=dict(
        fi="1. Myönteinen ja sitoutunut vuorovaikutus",
        sv=""),
    sensitiivinen_vuorovaikutus=dict(
        fi="3. Sensitiivinen vuorovaikutus",
        sv=""),
    yhdenvertainen_vuorovaikutus=dict(
        fi="5. Yhdenvertainen vuorovaikutus",
        sv=""),
    vastavuoroinen_vuorovaikutus=dict(
        fi="2. Vastavuoroinen vuorovaikutus",
        sv=""),
    kielellinen_vuorovaikutus=dict(
        fi="4. Kielellinen vuorovaikutus",
        sv=""),
    pedagoginen_prosessi=dict(
        fi="6. Pedagoginen suunnittelu, arviointi ja kehittäminen",
        sv=""),
    toiminnan_havainnointi=dict(
        fi="7. Toiminnan havainnointi ja dokumentointi",
        sv=""),
    monipuolinen_pedagoginen_toiminta=dict(
        fi="9. Monipuolinen pedagoginen toiminta",
        sv=""),
    toiminnan_merkityksellisyys=dict(
        fi="8. Toiminnan merkityksellisyys",
        sv=""),
    lapsen_yksilollisyyden_huom=dict(
        fi="10. Lapsen yksilöllisyyden huomioiminen",
        sv=""),
    perustoiminnot_ja_ruokailu=dict(
        fi="11. Perustoiminnot ja ruokailu",
        sv=""),
    paivittaiset_siirtymatilanteet=dict(
        fi="14. Päivittäiset siirtymätilanteet",
        sv=""),
    yksilollinen_tuki=dict(
        fi="12. Lapsen tuki",
        sv=""),
    oppimisymparisto=dict(
        fi="13. Oppimisympäristö",
        sv=""),
    pedagogiikan_johtaminen=dict(
        fi="15. Pedagogiikan johtaminen",
        sv=""),
    pedagoginen_vastuu=dict(
        fi="16. Pedagoginen vastuu",
        sv=""),
    myonteinen_oppimisymparisto=dict(
        fi="17. Myönteinen oppimisympäristö",
        sv=""),
    yhteisollinen_oppiminen=dict(
        fi="18. Yhteisöllinen oppiminen",
        sv=""),
    yhteenkuuluvuus=dict(
        fi="19. Yhteenkuuluvuus ja vertaisvuorovaikutus",
        sv=""),
    lapsen_kokemus=dict(
        fi="20. Lapsen kokemus",
        sv=""),
    moninaisuus=dict(
        fi="21. Moninaisuus",
        sv=""),
    moniammatillinen_vuorovaikutus=dict(
        fi="22. Ammatillinen vuorovaikutus",
        sv=""),
    yhteinen_ja_eriytynyt_ammat=dict(
        fi="23. Yhteinen ja eriytynyt ammatillinen osaaminen",
        sv=""),
    monialainen_yhteistyo=dict(
        fi="24. Monialainen yhteistyö",
        sv=""),
    kasvatusyhteistyo=dict(
        fi="25. Kasvatusyhteistyö",
        sv=""),
    huoltajien_osallisuus=dict(
        fi="26. Huoltajien osallisuus",
        sv=""),
    lainsaadannon_kehittaminen=dict(
        fi="1. Lainsäädännön kehittäminen",
        sv=""),
    suhdelukua_koskeva_lainsaadanto=dict(
        fi="2. Suhdelukua ja ryhmää koskeva lainsäädäntö",
        sv=""),
    henkiloston_kelpoisuusvaatimukset=dict(
        fi="3. Henkilöstön kelpoisuusvaatimukset",
        sv=""),
    toimintamuoto_lainsaadanto=dict(
        fi="4. Toimintamuotoja koskeva lainsäädäntö",
        sv=""),
    ohjausjarjestelma=dict(
        fi="5. Ohjausjärjestelmä ja inklusiiviset palvelut",
        sv=""),
    kansalliset_linjaukset=dict(
        fi="6. Lapsen tukeen liittyvät kansalliset linjaukset",
        sv=""),
    inklusiivisten_saatavuus=dict(
        fi="7. Inklusiivisten palveluiden saatavuus",
        sv=""),
    paikalliset_linjaukset=dict(
        fi="8. Lapsen tukeen liittyvät paikalliset linjaukset",
        sv=""),
    henkiloston_riittavyys=dict(
        fi="9. Henkilöstön riittävyys",
        sv=""),
    yhdenvertainen_osallistuminen=dict(
        fi="10. Lasten yhdenvertainen osallistuminen toimintaan",
        sv=""),
    kansallinen_opetussuunnitelma=dict(
        fi="11. Kansallinen opetussuunnitelma",
        sv=""),
    paikallinen_ops_tyovalineena=dict(
        fi="12. Paikallinen opetussuunnitelma työvälineenä",
        sv=""),
    paikallisen_opsn_arviointi=dict(
        fi="13. Paikallisen opetussuunnitelman arviointi",
        sv=""),
    koulutuksen_kansalliset_linjaukset=dict(
        fi="14. Perus- ja täydennyskoulutuksen kansalliset linjaukset",
        sv=""),
    paikallinen_taydennyskoulutus=dict(
        fi="15. Paikallinen täydennyskoulutus",
        sv=""),
    palveluohjaus_ja_toimintamuodot=dict(
        fi="16. Palveluohjaus ja toimintamuodot",
        sv=""),
    lasten_yhdenvertaisuus=dict(
        fi="17. Palveluohjaus ja lasten yhdenvertaisuus",
        sv=""),
    kansallinen_ohjausjarjestelma=dict(
        fi="18. Kansallinen ohjausjärjestelmä ja yksityiset palvelut",
        sv=""),
    yksityisten_palveluiden_ohjaus=dict(
        fi="19. Yksityisten palveluiden ohjaus, neuvonta ja valvonta",
        sv=""),
    siirtymat_koulutus_kasvatus=dict(
        fi="20. Siirtymät koulutus- ja kasvatusjärjestelmässä",
        sv=""),
    siirtymat_varhaiskasvatuksessa=dict(
        fi="21. Siirtymät varhaiskasvatuksessa",
        sv=""),
    siirtyma_kotoa_varhaiskasvatukseen=dict(
        fi="22. Siirtymä kotoa varhaiskasvatukseen",
        sv=""),
    siirtymien_suunnittelu_kaytannot=dict(
        fi="23. Siirtymien suunnittelu ja käytännöt",
        sv=""),
    kansallinen_arviointijarjestelma=dict(
        fi="24. Kansallinen arviointijärjestelmä",
        sv=""),
    paikallinen_laadunhallinta=dict(
        fi="25. Paikallinen laadunhallinta",
        sv=""),
    osallistava_arviointi_kehittaminen=dict(
        fi="26. Osallistava arviointi ja kehittäminen",
        sv=""),
    johtamisjarjestelma_ja_rakenteet=dict(
        fi="27. Johtamisjärjestelmä ja rakenteet",
        sv=""),
    tiedolla_johtaminen=dict(
        fi="28. Tiedolla johtaminen",
        sv=""),
    henkilosto_taloudelliset_resurssit=dict(
        fi="29. Henkilöstö- ja taloudelliset resurssit",
        sv=""),
    henkilostorakenne_ja_maara=dict(
        fi="30. Henkilöstörakenne ja -määrä",
        sv=""),
    tyoaikarakenteiden_suunnittelu=dict(
        fi="31. Työaikarakenteiden suunnittelu ja linjaukset",
        sv=""),
    osaamisen_hyodyntaminen=dict(
        fi="32. Työaikarakenteet ja henkilöstön osaamisen hyödyntäminen",
        sv=""),
    lapsiryhman_rakenne_ja_koko=dict(
        fi="33. Lapsiryhmän rakenne ja koko",
        sv=""),
    palautekysely=dict(
        fi="Ei indikaattoria",
        sv=""),
)
