# Generated by Django 4.0.5 on 2022-07-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VastausSend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=80)),
                ('vastaajatunnus', models.CharField(max_length=30)),
                ('vastaajaid', models.IntegerField()),
                ('language', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'vastaussend',
                'managed': True,
            },
        ),
    ]
