# Generated by Django 4.0.5 on 2022-09-06 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0002_vastaussend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vastaaja',
            fields=[
                ('vastaajaid', models.AutoField(primary_key=True, serialize=False)),
                ('kyselykertaid', models.IntegerField()),
                ('kyselyid', models.IntegerField()),
                ('vastaajatunnus', models.CharField(max_length=30)),
                ('tehtavanimikkeet', models.JSONField(default=dict)),
                ('tutkinnot', models.JSONField(default=dict)),
                ('luotuaika', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vastaaja',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='vastaussend',
            name='vastaajatunnus',
        ),
        migrations.AlterField(
            model_name='vastaus',
            name='vastaajaid',
            field=models.ForeignKey(db_column='vastaajaid', on_delete=django.db.models.deletion.DO_NOTHING, to='kyselyt.vastaaja'),
        ),
        migrations.AlterField(
            model_name='vastaussend',
            name='vastaajaid',
            field=models.ForeignKey(db_column='vastaajaid', on_delete=django.db.models.deletion.DO_NOTHING, to='kyselyt.vastaaja'),
        ),
    ]
