# Generated by Django 4.0.5 on 2022-10-18 13:06

from django.db import migrations, models

from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0003_vastaaja_remove_vastaussend_vastaajatunnus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('label_fi', models.CharField(blank=True, max_length=50, null=True)),
                ('label_sv', models.CharField(blank=True, max_length=50, null=True)),
                ('min_value', models.IntegerField()),
                ('max_value', models.IntegerField()),
                ('default_value', models.IntegerField()),
                ('step_count', models.IntegerField()),
                ('order_no', models.IntegerField(default=0)),
                ('eos_value', models.JSONField(null=True)),
                ('scale', models.JSONField()),
            ],
            options={
                'db_table': 'scale',
                'managed': settings.TESTING,
            },
        ),
    ]
