# Generated by Django 4.1.7 on 2023-03-31 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0004_scale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scale',
        ),
    ]
