# Generated by Django 4.1.10 on 2023-08-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0005_delete_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempVastaus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kysymysid', models.IntegerField()),
                ('vastaajatunnus', models.CharField(max_length=30)),
                ('kysely_voimassa_loppupvm', models.DateField(blank=True, null=True)),
                ('string', models.TextField(blank=True, null=True)),
                ('numerovalinta', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('en_osaa_sanoa', models.BooleanField(blank=True, null=True)),
                ('luotuaika', models.DateTimeField(auto_now_add=True)),
                ('muutettuaika', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tempvastaus',
                'managed': True,
            },
        ),
    ]
