# Generated by Django 4.1.11 on 2023-09-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0006_tempvastaus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempvastaus',
            name='kysymysid',
            field=models.CharField(max_length=30),
        ),
    ]
