# Generated by Django 4.2.5 on 2024-01-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0007_alter_tempvastaus_kysymysid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTaustatiedot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vastaajatunnus', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'failedtaustatiedot',
                'managed': True,
            },
        ),
    ]
