# Generated by Django 4.2.15 on 2024-08-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyselyt', '0008_failedtaustatiedot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempvastaus',
            name='string',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='vastaus',
            name='string',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
