import {
    RaporttiType,
    ReportingBase,
} from '@cscfi/shared/services/Raportointipalvelu-api/Raportointipalvelu-api-service';
import {
    KyselyType,
    StatusType,
    GenericFormValueType,
} from '../services/Data/Data-service';
import InputTypes from '../components/InputType/InputTypes';
import {
    ArvoKysely,
    ArvoKyselykerta,
    ArvoKyselySijainti,
} from '../services/Arvo-api/Arvo-api-service';

export const defaultValues: GenericFormValueType = {
    '1234_234': 'kysymys1',
    '1234_965': '',
    '1234_836': {1: false, 2: false},
};

const kyselyTopic = 'Kyselylomakkeen nimi';
const kysymysryhmaId = 1234;

export const kyselyData: KyselyType[] = [
    {
        id: kysymysryhmaId,
        topic: {fi: kyselyTopic, sv: ''},
        status: StatusType.luonnos,
        lomaketyyppi: 'henkilostolomake_prosessitekijat',
        paaIndikaattori: {group: 0, key: 'defaultIndikaattori'},
        kysymykset: [
            {
                id: 234,
                inputType: InputTypes.singletext,
                title: {fi: 'kysymys1', sv: 'fråga1'},
                description: {fi: 'ohje1 desc', sv: 'hljelppamandeerus1 desc'},
                required: false,
                answerOptions: [],
                matrixQuestions: [],
            },
            {
                id: 836,
                inputType: InputTypes.checkbox,
                title: {fi: 'kysymys2', sv: 'fråga2'},
                description: {fi: 'ohje2 desc', sv: 'hljelppamandeerus2 desc'},
                required: false,
                answerOptions: [
                    {
                        id: 1,
                        title: {fi: 'kyllä', sv: 'ja'},
                        description: {fi: '', sv: ''},
                        checked: false,
                    },
                    {
                        id: 2,
                        title: {fi: 'ei', sv: 'nej'},
                        description: {fi: '', sv: ''},
                        checked: false,
                    },
                ],
                matrixQuestions: [],
            },
            {
                id: 965,
                inputType: InputTypes.statictext,
                title: {fi: 'valiotsikko', sv: ''},
                required: false,
                description: {fi: 'sisaltoteksti', sv: ''},
                answerOptions: [],
                matrixQuestions: [],
            },
        ],
    },
];

export const arvoKyselytData: ArvoKysely[] = [
    {
        kysymysryhmat: [],
        automatisoitu: false,
        kaytettavissa: false,
        koulutustoimija: '123456-7',
        kyselyid: 123,
        kyselykerrat: [] as Array<ArvoKyselykerta>,
        kysymysryhmien_lkm: 1,
        metatiedot: {
            esikatselu_tunniste: 'hash',
            valssi_saate: 'saate',
            valssi_kysymysryhma: kysymysryhmaId,
        },
        nimi_en: '',
        nimi_fi: '',
        nimi_sv: '',
        selite_en: '',
        selite_fi: '',
        selite_sv: '',
        oppilaitos: '',
        poistettavissa: true,
        sijainti: 'julkaistu' as ArvoKyselySijainti,
        sivutettu: false,
        tila: 'julkaistu' as StatusType,
        tulevaisuudessa: false,
        uudelleenohjaus_url: '',
        vastaajatunnuksia: 0,
        vastaajia: 0,
        viimeisin_vastaus: '',
        voimassa_alkupvm: '2022-04-01T00:00:00.000Z',
        voimassa_loppupvm: '2022-08-05T00:00:00.000Z',
    },
];

export const raporttiPohja1Data: ReportingBase = {
    kysymysryhmaid: kysymysryhmaId,
    nimi_fi: 'Rapsapohjan nimi',
    nimi_sv: '',
    questions: [],
    reporting_template: {
        title_fi: 'test title',
        title_sv: 'test title',
        description_fi: 'test description',
        description_sv: 'test description',
        id: 1111,
        kysymysryhmaid: kysymysryhmaId,
        template_helptexts: [
            {
                id: 4321,
                question_id: 1234,
                title_fi: 'test title',
                title_sv: 'test title',
                description_fi: 'test description',
                description_sv: 'test description',
            },
        ],
    },
    job_titles_fi: undefined,
    job_titles_sv: undefined,
};

export const raporttiPohja2Data: ReportingBase = {
    kysymysryhmaid: kysymysryhmaId,
    nimi_fi: 'Rapsapohjan nimi',
    nimi_sv: '',
    questions: [],
    reporting_template: {
        title_fi: '',
        title_sv: '',
        description_fi: '',
        description_sv: '',
        kysymysryhmaid: null,
        template_helptexts: [],
    },
    job_titles_fi: undefined,
    job_titles_sv: undefined,
};

export const raporttiData: RaporttiType = {
    kysymysryhmaid: kysymysryhmaId,
    nimi_fi: 'Raportin nimi',
    nimi_sv: '',
    job_titles_fi: undefined,
    job_titles_sv: undefined,
    koulutustoimija_nimi_fi: 'Koulutustoimija_fi',
    koulutustoimija_nimi_sv: 'Koulutustoimija_sv',
    survey_participants_count: 0,
    survey_sent_count: 0,
    reporting_base: {
        kysymysryhmaid: kysymysryhmaId,
        nimi_fi: 'Kysymysryhmän nimi fi',
        nimi_sv: 'Kysymysryhmän nimi sv',
        job_titles_fi: undefined,
        job_titles_sv: undefined,
        questions: undefined,
        reporting_template: {
            kysymysryhmaid: kysymysryhmaId,
            title_fi: null,
            title_sv: null,
            template_helptexts: [],
            description_fi: 'Helping text for interpreting the report FI',
            description_sv: 'Helping text for interpreting the report SV',
        },
    },
};

export const kysymysryhmaData = {
    tila: StatusType.luonnos,
    nimi_fi: kyselyTopic,
    kuvaus_sv: null,
    nimi_sv: null,
    selite_fi: null,
    kysymysryhmaid: kysymysryhmaId,
    selite_sv: null,
    selite_en: null,
    metatiedot: {
        paaIndikaattori: 'paaIndikaattori',
        sekondaariset_indikaattorit: ['sekondaarinen_indikaattori'],
        lomaketyyppi: 'henkilostolomake_prosessitekijat',
    },
    kysymykset: [
        {
            muutettu_kayttaja: '1.2.246.562.24.91714597546',
            eos_vastaus_sallittu: null,
            kysymys_en: null,
            kysymysryhma_sv: null,
            kysymys_metatiedot: {
                type: 'string',
                numeric: false,
                multiline: false,
                description: {fi: '', sv: ''},
            },
            jarjestys: 0,
            poistettava: true,
            jatkokysymys: false,
            kysymysryhma_fi: kyselyTopic,
            selite_fi: null,
            jatkokysymys_kysymysid: null,
            kysymysryhmaid: kysymysryhmaId,
            selite_sv: null,
            max_vastaus: null,
            monivalinta_max: null,
            metatiedot: {
                type: 'string',
                numeric: false,
                multiline: false,
                description: {fi: '', sv: ''},
            },
            taustakysymys: false,
            selite_en: null,
            luotuaika: '2022-03-08T06:14:44.332Z',
            kysymysryhma_sn: null,
            pakollinen: false,
            jatkokysymys_vastaus: null,
            luotu_kayttaja: '1.2.246.562.24.98742609357',
            kysymysid: 234,
            rajoite: null,
            raportoitava: true,
            matriisi_jarjestys: null,
            vastaustyyppi: 'string',
            muutettuaika: '2022-03-11T13:58:19.720Z',
            matriisi_kysymysid: null,
            kysymys_sv: 'fråga1',
            kysymys_fi: 'kysymys1',
        },
        {
            muutettu_kayttaja: '1.2.246.562.24.91714597546',
            eos_vastaus_sallittu: null,
            kysymys_en: null,
            kysymysryhma_sv: null,
            kysymys_metatiedot: {
                type: 'checkbox',
                vastausvaihtoehdot: [
                    {
                        id: 1,
                        label: 'kyllä',
                        checked: false,
                    },
                    {
                        id: 2,
                        label: 'ei',
                        checked: false,
                    },
                ],
            },
            jarjestys: 1,
            poistettava: true,
            jatkokysymys: false,
            kysymysryhma_fi: 'ssd23',
            selite_fi: null,
            jatkokysymys_kysymysid: null,
            kysymysryhmaid: kysymysryhmaId,
            selite_sv: null,
            max_vastaus: null,
            monivalinta_max: null,
            metatiedot: {
                type: 'checkbox',
                vastausvaihtoehdot: [
                    {
                        id: 1,
                        label: 'kyllä',
                        checked: false,
                    },
                    {
                        id: 2,
                        label: 'ei',
                        checked: false,
                    },
                ],
            },
            taustakysymys: false,
            selite_en: null,
            luotuaika: '2022-03-22T10:50:41.580Z',
            kysymysryhma_sn: null,
            monivalintavaihtoehdot: [],
            pakollinen: false,
            jatkokysymys_vastaus: null,
            luotu_kayttaja: '1.2.246.562.24.91714597546',
            kysymysid: 836,
            rajoite: null,
            raportoitava: true,
            matriisi_jarjestys: null,
            vastaustyyppi: 'monivalinta',
            muutettuaika: '2022-03-22T10:50:41.580Z',
            matriisi_kysymysid: null,
            kysymys_sv: '',
            kysymys_fi: 'kysymys2',
        },
        {
            muutettu_kayttaja: '1.2.246.562.24.91714597546',
            eos_vastaus_sallittu: null,
            kysymys_en: null,
            kysymysryhma_sv: null,
            kysymys_metatiedot: {
                type: 'string',
                numeric: false,
                multiline: false,
                description: {fi: '', sv: ''},
            },
            jarjestys: 0,
            poistettava: true,
            jatkokysymys: false,
            kysymysryhma_fi: kyselyTopic,
            selite_fi: null,
            jatkokysymys_kysymysid: null,
            kysymysryhmaid: kysymysryhmaId,
            selite_sv: null,
            max_vastaus: null,
            monivalinta_max: null,
            metatiedot: {
                type: 'string',
                numeric: false,
                multiline: false,
                description: {fi: '', sv: ''},
                hidden: true,
            },
            taustakysymys: false,
            selite_en: null,
            luotuaika: '2022-03-08T06:14:44.332Z',
            kysymysryhma_sn: null,
            pakollinen: false,
            jatkokysymys_vastaus: null,
            luotu_kayttaja: '1.2.246.562.24.98742609357',
            kysymysid: 235,
            rajoite: null,
            raportoitava: true,
            matriisi_jarjestys: null,
            vastaustyyppi: 'string',
            muutettuaika: '2022-03-11T13:58:19.820Z',
            matriisi_kysymysid: null,
            kysymys_sv: 'hiddenFråga3',
            kysymys_fi: 'hiddenKysymys3',
        },
        {
            muutettu_kayttaja: '1.2.246.562.24.91714597546',
            eos_vastaus_sallittu: null,
            kysymys_en: null,
            kysymysryhma_sv: null,
            kysymys_metatiedot: {
                type: 'string',
                numeric: false,
                multiline: true,
                description: {
                    fi: 'sisaltoteksti',
                    sv: '',
                },
            },
            jarjestys: 2,
            poistettava: true,
            jatkokysymys: false,
            kysymysryhma_fi: 'ssd23',
            selite_fi: null,
            jatkokysymys_kysymysid: null,
            kysymysryhmaid: kysymysryhmaId,
            selite_sv: null,
            max_vastaus: null,
            monivalinta_max: null,
            metatiedot: {
                type: 'string',
                numeric: false,
                multiline: true,
                description: {
                    fi: 'sisaltoteksti',
                    sv: '',
                },
            },
            taustakysymys: false,
            selite_en: null,
            luotuaika: '2022-03-22T10:51:19.827Z',
            kysymysryhma_sn: null,
            pakollinen: false,
            jatkokysymys_vastaus: null,
            luotu_kayttaja: '1.2.246.562.24.91714597546',
            kysymysid: 965,
            rajoite: null,
            raportoitava: true,
            matriisi_jarjestys: null,
            vastaustyyppi: 'string',
            muutettuaika: '2022-03-22T10:51:19.827Z',
            matriisi_kysymysid: null,
            kysymys_sv: '',
            kysymys_fi: 'valiotsikko',
        },
    ],
    kuvaus_fi: null,
    taustakysymykset: false,
    valtakunnallinen: false,
    kuvaus_en: null,
    nimi_en: null,
};

export const kyselyKertaData = {
    kysely: {
        nimi_en: null,
        nimi_fi: 'testikysely fi',
        nimi_sv: 'testikysely sv',
        kyselyid: 123,
        kysymysryhmat: [
            {
                jarjestys: 0,
                kysymysryhma: kysymysryhmaData,
            },
        ],
        metatiedot: {
            esikatselu_tunniste: 'qweqweqweqweqweqweqwe',
            valssi_kysymysryhma: kysymysryhmaId,
            valssi_saate: 'testisaate',
        },
        sivutettu: false,
        tila: 'julkaistu',
        tyyppi: 'henkilostolomake_prosessitekijat',
        uudelleenohjaus_url: null,
        voimassa_alkupvm: '2023-01-01',
        voimassa_loppupvm: '2030-12-31',
    },
    kyselykertaid: 1234,
    nimi: 'testikyselykerta',
    tempvastaus_allowed: true,
    voimassa_alkupvm: '2023-01-01',
    voimassa_loppupvm: '2030-12-31',
};

export const yllapitajaUserData = {
    rooli: {kayttooikeus: 'YLLAPITAJA'},
    rooliManipuloitu: false,
    nimi: 'Testi Käyttäjä',
    arvoRoolit: [{kayttooikeus: 'YLLAPITAJA'}],
    arvoAktiivinenRooli: {kayttooikeus: 'YLLAPITAJA'},
    organisaatio: 'Testiorganisaatio',
};

export const paakayttajaUserData = {
    rooli: {kayttooikeus: 'PAAKAYTTAJA'},
    rooliManipuloitu: false,
    nimi: 'Testi Käyttäjä',
    arvoRoolit: [{kayttooikeus: 'PAAKAYTTAJA'}],
    arvoAktiivinenRooli: {kayttooikeus: 'PAAKAYTTAJA'},
    organisaatio: 'Testiorganisaatio',
};

export default kyselyData;
