import {
    RaporttiType,
    ReportingBase,
} from '@cscfi/shared/services/Raportointipalvelu-api/Raportointipalvelu-api-service';
import {UserInfoType} from '@cscfi/shared/services/Login/Login-service';
import {IndikaattoriGroupType} from '@cscfi/shared/services/Virkailijapalvelu-api/Virkailijapalvelu-api-service';
import {
    KyselyType,
    StatusType,
    GenericFormValueType,
    SekondaarinenIndikaattoriType,
} from '../services/Data/Data-service';
import InputTypes from '../components/InputType/InputTypes';
import {
    ArvoKysely,
    ArvoKyselykerta,
    ArvoKyselySijainti,
    ArvoKysymysryhma,
} from '../services/Arvo-api/Arvo-api-service';

export const defaultValues: GenericFormValueType = {
    '1234_234': 'kysymys1',
    '1234_965': '',
    '1234_836': {1: false, 2: false},
};

const kyselyTopic = 'Kyselylomakkeen nimi';
const kysymysryhmaId = 1234;

export const kyselyData: KyselyType[] = [
    {
        id: kysymysryhmaId,
        topic: {fi: kyselyTopic, sv: ''},
        status: StatusType.luonnos,
        lomaketyyppi: 'henkilostolomake_prosessitekijat',
        paaIndikaattori: {group: 0, key: 'defaultIndikaattori'},
        kysymykset: [
            {
                id: 234,
                inputType: InputTypes.singletext,
                title: {fi: 'kysymys1', sv: 'fråga1'},
                description: {fi: 'ohje1 desc', sv: 'hljelppamandeerus1 desc'},
                required: false,
                answerOptions: [],
                matrixQuestions: [],
                pagebreak: false,
                page: 0,
                metatiedot: {
                    pagebreak: false,
                    description: {fi: '', sv: ''},
                    hidden: false,
                    is_hidden_on_report: false,
                },
            },
            {
                id: 836,
                inputType: InputTypes.checkbox,
                title: {fi: 'kysymys2', sv: 'fråga2'},
                description: {fi: 'ohje2 desc', sv: 'hljelppamandeerus2 desc'},
                required: false,
                answerOptions: [
                    {
                        id: 1,
                        title: {fi: 'kyllä', sv: 'ja'},
                        description: {fi: '', sv: ''},
                        checked: false,
                    },
                    {
                        id: 2,
                        title: {fi: 'ei', sv: 'nej'},
                        description: {fi: '', sv: ''},
                        checked: false,
                    },
                ],
                matrixQuestions: [],
                pagebreak: false,
                page: 0,
                metatiedot: {
                    pagebreak: false,
                    description: {fi: '', sv: ''},
                    hidden: false,
                    is_hidden_on_report: false,
                },
            },
            {
                id: 965,
                inputType: InputTypes.statictext,
                title: {fi: 'valiotsikko', sv: ''},
                required: false,
                description: {fi: 'sisaltoteksti', sv: ''},
                answerOptions: [],
                matrixQuestions: [],
                pagebreak: true,
                page: 0,
                metatiedot: {
                    pagebreak: false,
                    description: {fi: '', sv: ''},
                    hidden: false,
                    is_hidden_on_report: false,
                },
            },
            {
                id: 966,
                inputType: InputTypes.numeric,
                title: {fi: 'numerokysymys sivulla 2', sv: 'sv sivu 2'},
                required: false,
                description: {fi: 'kuvaus', sv: 'beskrivning'},
                answerOptions: [],
                matrixQuestions: [],
                pagebreak: false,
                page: 1,
                metatiedot: {
                    pagebreak: false,
                    description: {fi: '', sv: ''},
                    hidden: false,
                    is_hidden_on_report: false,
                },
            },
        ],
    },
];

export const arvoKyselytData: ArvoKysely[] = [
    {
        kysymysryhmat: [],
        automatisoitu: false,
        kaytettavissa: false,
        koulutustoimija: '123456-7',
        kyselyid: 123,
        kyselykerrat: [] as Array<ArvoKyselykerta>,
        kysymysryhmien_lkm: 1,
        metatiedot: {
            esikatselu_tunniste: 'hash',
            valssi_saate: 'saate',
            valssi_kysymysryhma: kysymysryhmaId,
        },
        nimi_en: '',
        nimi_fi: '',
        nimi_sv: '',
        selite_en: '',
        selite_fi: '',
        selite_sv: '',
        oppilaitos: '',
        poistettavissa: true,
        sijainti: 'julkaistu' as ArvoKyselySijainti,
        sivutettu: false,
        tila: 'julkaistu' as StatusType,
        tulevaisuudessa: false,
        uudelleenohjaus_url: '',
        vastaajatunnuksia: 0,
        vastaajia: 0,
        viimeisin_vastaus: '',
        voimassa_alkupvm: '2022-04-01T00:00:00.000Z',
        voimassa_loppupvm: '2022-08-05T00:00:00.000Z',
    },
];

export const raporttiPohja1Data: ReportingBase = {
    kysymysryhmaid: kysymysryhmaId,
    nimi_fi: 'Rapsapohjan nimi',
    nimi_sv: '',
    questions: [],
    reporting_template: {
        title_fi: 'test title',
        title_sv: 'test title',
        description_fi: 'test description',
        description_sv: 'test description',
        id: 1111,
        kysymysryhmaid: kysymysryhmaId,
        template_helptexts: [
            {
                id: 4321,
                question_id: 1234,
                title_fi: 'test title',
                title_sv: 'test title',
                description_fi: 'test description',
                description_sv: 'test description',
            },
        ],
    },
    job_titles_fi: [],
    job_titles_sv: [],
};

export const raporttiPohja2Data: ReportingBase = {
    kysymysryhmaid: kysymysryhmaId,
    nimi_fi: 'Rapsapohjan nimi',
    nimi_sv: '',
    questions: [],
    reporting_template: {
        title_fi: '',
        title_sv: '',
        description_fi: '',
        description_sv: '',
        kysymysryhmaid: kysymysryhmaId,
        template_helptexts: [],
    },
    job_titles_fi: [],
    job_titles_sv: [],
};

export const raporttiData: RaporttiType = {
    kysymysryhmaid: kysymysryhmaId,
    nimi_fi: 'Raportin nimi',
    nimi_sv: '',
    job_titles_fi: [],
    job_titles_sv: [],
    koulutustoimija_nimi_fi: 'Koulutustoimija_fi',
    koulutustoimija_nimi_sv: 'Koulutustoimija_sv',
    survey_participants_count: 0,
    survey_sent_count: 0,
    survey_oppilaitoses_activated_count: 0,
    survey_oppilaitoses_answered_count: 0,
    language_codes: [],
    aluejako_alueet: [
        {id: 3, name: {fi: 'alue 1', sv: 'gr1'}},
        {id: 5, name: {fi: 'alue 2', sv: 'gr2'}},
    ],
    reporting_base: {
        kysymysryhmaid: kysymysryhmaId,
        nimi_fi: 'Kysymysryhmän nimi fi',
        nimi_sv: 'Kysymysryhmän nimi sv',
        job_titles_fi: [],
        job_titles_sv: [],
        questions: [],
        reporting_template: {
            kysymysryhmaid: kysymysryhmaId,
            title_fi: '',
            title_sv: '',
            template_helptexts: [],
            description_fi: 'Helping text for interpreting the report FI',
            description_sv: 'Helping text for interpreting the report SV',
        },
    },
};

export const mockIndikaattoriGroup = {
    group_id: 1001,
    indicators: [
        {
            key: 'paaIndikaattori',
            group_id: 1,
            laatutekija: 'asdf',
        } as SekondaarinenIndikaattoriType,
    ],
} as IndikaattoriGroupType;

export const kysymysryhmaData = {
    tila: StatusType.luonnos,
    nimi_fi: kyselyTopic,
    kuvaus_sv: undefined,
    nimi_sv: undefined,
    selite_fi: undefined,
    kysymysryhmaid: kysymysryhmaId,
    selite_sv: undefined,
    selite_en: undefined,
    muutettuaika: '2024-07-05',
    metatiedot: {
        paaIndikaattori: {key: 'paaIndikaattori', group: 1},
        sekondaariset_indikaattorit: [{key: 'sekondaarinen_indikaattori_1'}],
        lomaketyyppi: 'henkilostolomake_prosessitekijat',
    },
    kysymykset: [
        {
            kysymysid: 234,
            kysymys_fi: 'kysymys1',
            kysymys_sv: 'fråga1',
            kysymys_en: undefined,
            muutettu_kayttaja: '1.2.246.562.24.91714597546',
            eos_vastaus_sallittu: undefined,
            kysymysryhma_sv: undefined,
            kysymys_metatiedot: {
                type: 'string',
                numeric: false,
                multiline: false,
                description: {fi: '', sv: ''},
            },
            jarjestys: 0,
            poistettava: true,
            jatkokysymys: false,
            kysymysryhma_fi: kyselyTopic,
            selite_fi: undefined,
            jatkokysymys_kysymysid: undefined,
            kysymysryhmaid: kysymysryhmaId,
            selite_sv: undefined,
            max_vastaus: undefined,
            monivalinta_max: undefined,
            metatiedot: {
                type: 'string',
                numeric: false,
                multiline: false,
                description: {fi: '', sv: ''},
            },
            taustakysymys: false,
            selite_en: undefined,
            luotuaika: '2022-03-08T06:14:44.332Z',
            kysymysryhma_sn: undefined,
            pakollinen: false,
            jatkokysymys_vastaus: undefined,
            luotu_kayttaja: '1.2.246.562.24.98742609357',
            rajoite: undefined,
            raportoitava: true,
            matriisi_jarjestys: undefined,
            vastaustyyppi: 'string',
            muutettuaika: '2022-03-11T13:58:19.720Z',
            matriisi_kysymysid: undefined,
        },
        {
            muutettu_kayttaja: '1.2.246.562.24.91714597546',
            eos_vastaus_sallittu: undefined,
            kysymys_en: undefined,
            kysymysryhma_sv: undefined,
            kysymys_metatiedot: {
                type: 'checkbox',
                vastausvaihtoehdot: [
                    {
                        id: 1,
                        label: 'kyllä',
                        checked: false,
                    },
                    {
                        id: 2,
                        label: 'ei',
                        checked: false,
                    },
                ],
            },
            jarjestys: 1,
            poistettava: true,
            jatkokysymys: false,
            kysymysryhma_fi: 'ssd23',
            selite_fi: undefined,
            jatkokysymys_kysymysid: undefined,
            kysymysryhmaid: kysymysryhmaId,
            selite_sv: undefined,
            max_vastaus: undefined,
            monivalinta_max: undefined,
            metatiedot: {
                type: 'checkbox',
                vastausvaihtoehdot: [
                    {
                        id: 1,
                        label: 'kyllä',
                        checked: false,
                    },
                    {
                        id: 2,
                        label: 'ei',
                        checked: false,
                    },
                ],
            },
            taustakysymys: false,
            selite_en: undefined,
            luotuaika: '2022-03-22T10:50:41.580Z',
            kysymysryhma_sn: undefined,
            monivalintavaihtoehdot: [],
            pakollinen: false,
            jatkokysymys_vastaus: undefined,
            luotu_kayttaja: '1.2.246.562.24.91714597546',
            kysymysid: 836,
            rajoite: undefined,
            raportoitava: true,
            matriisi_jarjestys: undefined,
            vastaustyyppi: 'monivalinta',
            muutettuaika: '2022-03-22T10:50:41.580Z',
            matriisi_kysymysid: undefined,
            kysymys_sv: '',
            kysymys_fi: 'kysymys2',
        },
        {
            kysymys_sv: 'hiddenFråga3',
            kysymys_fi: 'hiddenKysymys3',
            muutettu_kayttaja: '1.2.246.562.24.91714597546',
            eos_vastaus_sallittu: undefined,
            kysymys_en: undefined,
            kysymysryhma_sv: undefined,
            kysymys_metatiedot: {
                type: 'string',
                numeric: false,
                multiline: false,
                description: {fi: '', sv: ''},
            },
            jarjestys: 2,
            poistettava: true,
            jatkokysymys: false,
            kysymysryhma_fi: kyselyTopic,
            selite_fi: undefined,
            jatkokysymys_kysymysid: undefined,
            kysymysryhmaid: kysymysryhmaId,
            selite_sv: undefined,
            max_vastaus: undefined,
            monivalinta_max: undefined,
            metatiedot: {
                type: 'string',
                numeric: false,
                multiline: false,
                description: {fi: '', sv: ''},
                hidden: true,
                pagebreak: true,
            },
            taustakysymys: false,
            selite_en: undefined,
            luotuaika: '2022-03-08T06:14:44.332Z',
            kysymysryhma_sn: undefined,
            pakollinen: false,
            jatkokysymys_vastaus: undefined,
            luotu_kayttaja: '1.2.246.562.24.98742609357',
            kysymysid: 235,
            rajoite: undefined,
            raportoitava: true,
            matriisi_jarjestys: undefined,
            vastaustyyppi: 'string',
            muutettuaika: '2022-03-11T13:58:19.820Z',
            matriisi_kysymysid: undefined,
        },
        {
            kysymys_sv: '',
            kysymys_fi: 'valiotsikko',
            selite_fi: 'this question is on page 2',
            muutettu_kayttaja: '1.2.246.562.24.91714597546',
            eos_vastaus_sallittu: undefined,
            kysymys_en: undefined,
            kysymysryhma_sv: undefined,
            kysymys_metatiedot: {
                type: 'string',
                numeric: false,
                multiline: true,
                description: {
                    fi: 'sisaltoteksti',
                    sv: '',
                },
            },
            jarjestys: 3,
            poistettava: true,
            jatkokysymys: false,
            kysymysryhma_fi: 'ssd23',
            jatkokysymys_kysymysid: undefined,
            kysymysryhmaid: kysymysryhmaId,
            selite_sv: undefined,
            max_vastaus: undefined,
            monivalinta_max: undefined,
            metatiedot: {
                type: 'string',
                numeric: false,
                multiline: true,
                description: {
                    fi: 'sisaltoteksti',
                    sv: '',
                },
            },
            taustakysymys: false,
            selite_en: undefined,
            luotuaika: '2022-03-22T10:51:19.827Z',
            kysymysryhma_sn: undefined,
            pakollinen: false,
            jatkokysymys_vastaus: undefined,
            luotu_kayttaja: '1.2.246.562.24.91714597546',
            kysymysid: 965,
            rajoite: undefined,
            raportoitava: true,
            matriisi_jarjestys: undefined,
            vastaustyyppi: 'string',
            muutettuaika: '2022-03-22T10:51:19.827Z',
            matriisi_kysymysid: undefined,
        },
    ],
    kuvaus_fi: undefined,
    taustakysymykset: false,
    valtakunnallinen: false,
    kuvaus_en: undefined,
    nimi_en: undefined,
} as ArvoKysymysryhma;

export const kyselyKertaData = {
    kysely: {
        nimi_en: null,
        nimi_fi: 'testikysely fi',
        nimi_sv: 'testikysely sv',
        kyselyid: 123,
        kysymysryhmat: [
            {
                jarjestys: 0,
                kysymysryhma: kysymysryhmaData,
            },
        ],
        metatiedot: {
            esikatselu_tunniste: 'qweqweqweqweqweqweqwe',
            valssi_kysymysryhma: kysymysryhmaId,
            valssi_saate: 'testisaate',
        },
        sivutettu: false,
        tila: 'julkaistu',
        tyyppi: 'henkilostolomake_prosessitekijat',
        uudelleenohjaus_url: null,
        voimassa_alkupvm: '2023-01-01',
        voimassa_loppupvm: '2030-12-31',
    },
    kyselykertaid: 1234,
    nimi: 'testikyselykerta',
    tempvastaus_allowed: true,
    voimassa_alkupvm: '2023-01-01',
    voimassa_loppupvm: '2030-12-31',
};

export const yllapitajaUserData = {
    rooli: {kayttooikeus: 'YLLAPITAJA'},
    rooliManipuloitu: false,
    nimi: 'Testi Käyttäjä',
    arvoRoolit: [{kayttooikeus: 'YLLAPITAJA'}],
    arvoAktiivinenRooli: {kayttooikeus: 'YLLAPITAJA'},
    organisaatio: 'Testiorganisaatio',
} as UserInfoType;

export const paakayttajaUserData = {
    rooli: {kayttooikeus: 'PAAKAYTTAJA'},
    rooliManipuloitu: false,
    nimi: 'Testi Käyttäjä',
    arvoRoolit: [{kayttooikeus: 'PAAKAYTTAJA'}],
    arvoAktiivinenRooli: {kayttooikeus: 'PAAKAYTTAJA'},
    organisaatio: 'Testiorganisaatio',
} as UserInfoType;

export const matrixScales = [
    {
        name: 'toteutuu-asteikko',
        order_no: 1,
        label: {
            fi: 'Toteutuu-asteikko',
            sv: 'Genomförs skala',
        },
        min_value: 1,
        max_value: 5,
        default_value: 3,
        step_count: 5,
        scale: [
            {
                fi: 'toteutuu erittäin heikosti',
                sv: 'genomförs mycket dåligt',
                value: 1,
            },
            {
                fi: 'toteutuu heikosti',
                sv: 'genomförs dåligt',
                value: 2,
            },
            {
                fi: 'toteutuu kohtalaisesti',
                sv: 'genomförs någorlunda',
                value: 3,
            },
            {
                fi: 'toteutuu hyvin',
                sv: 'genomförs väl',
                value: 4,
            },
            {
                fi: 'toteutuu erittäin hyvin',
                sv: 'genomförs mycket väl',
                value: 5,
            },
        ],
        is_visible: true,
        eos_allowed: true,
        eos_value: {
            fi: 'ei koske ryhmääni',
            sv: 'gäller inte min grupp',
            value: 0,
        },
    },
    {
        name: 'toteutuu_ekm',
        order_no: 2,
        label: {
            fi: 'Toteutuu EKM',
            sv: 'Genomförs GIM',
        },
        min_value: 1,
        max_value: 5,
        default_value: 3,
        step_count: 5,
        scale: [
            {
                fi: 'toteutuu erittäin heikosti',
                sv: 'genomförs mycket dåligt',
                value: 1,
            },
            {
                fi: 'toteutuu heikosti',
                sv: 'genomförs dåligt',
                value: 2,
            },
            {
                fi: 'toteutuu kohtalaisesti',
                sv: 'genomförs någorlunda',
                value: 3,
            },
            {
                fi: 'toteutuu hyvin',
                sv: 'genomförs väl',
                value: 4,
            },
            {
                fi: 'toteutuu erittäin hyvin',
                sv: 'genomförs mycket väl',
                value: 5,
            },
        ],
        is_visible: true,
        eos_allowed: true,
        eos_value: {
            fi: 'ei koske minua',
            sv: 'gäller inte mig',
            value: 0,
        },
    },
    {
        name: 'kuinka_usein_6',
        order_no: 3,
        label: {
            fi: 'Kuinka usein 6',
            sv: 'Hur ofta 6',
        },
        min_value: 1,
        max_value: 6,
        default_value: 3,
        step_count: 6,
        scale: [
            {
                fi: 'harvemmin kuin kerran kuukaudessa',
                sv: 'mer sällan än en gång i månaden',
                value: 1,
            },
            {
                fi: 'kerran kuukaudessa',
                sv: 'en gång i månaden',
                value: 2,
            },
            {
                fi: '2-3 kertaa kuukaudessa',
                sv: '2-3 gånger i månaden',
                value: 3,
            },
            {
                fi: 'kerran viikossa',
                sv: 'en gång i veckan',
                value: 4,
            },
            {
                fi: '2-3 kertaa viikossa',
                sv: '2-3 gånger i veckan',
                value: 5,
            },
            {
                fi: 'päivittäin',
                sv: 'dagligen',
                value: 6,
            },
        ],
        is_visible: true,
        eos_allowed: true,
        eos_value: {
            fi: 'ei koske ryhmääni',
            sv: 'gäller inte min grupp',
            value: 0,
        },
    },
    {
        name: 'kuinka_usein_5',
        order_no: 4,
        label: {
            fi: 'Kuinka usein 5',
            sv: 'Hur ofta 5',
        },
        min_value: 1,
        max_value: 5,
        default_value: 3,
        step_count: 5,
        scale: [
            {
                fi: 'ei koskaan',
                sv: 'aldrig',
                value: 1,
            },
            {
                fi: 'harvemmin kuin kerran kuukaudessa',
                sv: 'mer sällan än en gång i månaden',
                value: 2,
            },
            {
                fi: 'kuukausittain',
                sv: 'varje månad',
                value: 3,
            },
            {
                fi: 'viikoittain',
                sv: 'varje vecka',
                value: 4,
            },
            {
                fi: 'päivittäin',
                sv: 'dagligen',
                value: 5,
            },
        ],
        is_visible: true,
        eos_allowed: true,
        eos_value: {
            fi: 'ei koske ryhmääni',
            sv: 'gäller inte min grupp',
            value: 0,
        },
    },
    {
        name: 'kylla_ei_valinta',
        order_no: 5,
        label: {
            fi: 'Kyllä-ei',
            sv: 'ja-nej',
        },
        min_value: 1,
        max_value: 2,
        default_value: 1,
        step_count: 2,
        scale: [
            {
                fi: 'ei',
                sv: 'nej',
                value: 1,
            },
            {
                fi: 'kyllä',
                sv: 'ja',
                value: 2,
            },
        ],
        is_visible: true,
        eos_allowed: true,
        eos_value: {
            fi: 'ei koske ryhmääni',
            sv: 'gäller inte min grupp',
            value: 0,
        },
    },
    {
        name: 'olen_lukenut',
        order_no: 6,
        label: {
            fi: 'Olen lukenut',
            sv: 'Jag har läst',
        },
        min_value: 1,
        max_value: 3,
        default_value: 2,
        step_count: 3,
        scale: [
            {
                fi: 'en ole lukenut',
                sv: 'jag har inte läst',
                value: 1,
            },
            {
                fi: 'olen lukenut osittain',
                sv: 'jag har läst delvis',
                value: 2,
            },
            {
                fi: 'olen lukenut kokonaan',
                sv: 'jag har läst i sin helhet',
                value: 3,
            },
        ],
        is_visible: true,
        eos_allowed: true,
        eos_value: {
            fi: 'ei koske minua',
            sv: 'gäller inte mig',
            value: 0,
        },
    },
    {
        name: 'likert_asteikko',
        order_no: 7,
        label: {
            fi: 'Likert-asteikko',
            sv: 'Likertskala',
        },
        min_value: 1,
        max_value: 5,
        default_value: 3,
        step_count: 5,
        scale: [
            {
                fi: 'täysin eri mieltä',
                sv: 'helt av annan åsikt',
                value: 1,
            },
            {
                fi: 'jokseenkin eri mieltä',
                sv: 'delvis av annan åsikt',
                value: 2,
            },
            {
                fi: 'ei eri eikä samaa mieltä',
                sv: 'varken av annan eller av samma åsikt',
                value: 3,
            },
            {
                fi: 'jokseenkin samaa mieltä',
                sv: 'delvis av samma åsikt',
                value: 4,
            },
            {
                fi: 'täysin samaa mieltä',
                sv: 'helt av samma åsikt',
                value: 5,
            },
        ],
        is_visible: true,
        eos_allowed: true,
        eos_value: {
            fi: 'ei koske ryhmääni',
            sv: 'gäller inte min grupp',
            value: 0,
        },
    },
    {
        name: 'likert_ekm',
        order_no: 8,
        label: {
            fi: 'Likert-asteikko EKM',
            sv: 'Likertskala GIM',
        },
        min_value: 1,
        max_value: 5,
        default_value: 3,
        step_count: 5,
        scale: [
            {
                fi: 'täysin eri mieltä',
                sv: 'helt av annan åsikt',
                value: 1,
            },
            {
                fi: 'jokseenkin eri mieltä',
                sv: 'delvis av annan åsikt',
                value: 2,
            },
            {
                fi: 'ei eri eikä samaa mieltä',
                sv: 'varken av annan eller av samma åsikt',
                value: 3,
            },
            {
                fi: 'jokseenkin samaa mieltä',
                sv: 'delvis av samma åsikt',
                value: 4,
            },
            {
                fi: 'täysin samaa mieltä',
                sv: 'helt av samma åsikt',
                value: 5,
            },
        ],
        is_visible: true,
        eos_allowed: true,
        eos_value: {
            fi: 'ei koske minua',
            sv: 'gäller inte mig',
            value: 0,
        },
    },
    {
        name: 'toteutuminen',
        order_no: 9,
        label: {
            fi: 'Toteutuminen',
            sv: 'Förverkligas',
        },
        min_value: 1,
        max_value: 4,
        default_value: 2,
        step_count: 4,
        scale: [
            {
                fi: 'ei toteudu',
                sv: 'genomförs inte',
                value: 1,
            },
            {
                fi: 'toteutuu osittain',
                sv: 'genomförs delvis',
                value: 2,
            },
            {
                fi: 'toteutuu kokonaan',
                sv: 'genomförs helt',
                value: 3,
            },
            {
                fi: 'ei koske kuntaamme',
                sv: 'gäller inte vår kommun',
                value: 4,
            },
        ],
        is_visible: true,
        eos_allowed: true,
        eos_value: {
            fi: 'ei koske ryhmääni',
            sv: 'gäller inte min grupp',
            value: 0,
        },
    },
    {
        name: 'toteutuminen_3',
        order_no: 10,
        label: {
            fi: 'Toteutuminen 3',
            sv: 'Förverkligas 3',
        },
        min_value: 1,
        max_value: 3,
        default_value: 2,
        step_count: 3,
        scale: [
            {
                fi: 'ei toteudu',
                sv: 'genomförs inte',
                value: 1,
            },
            {
                fi: 'toteutuu osittain',
                sv: 'genomförs delvis',
                value: 2,
            },
            {
                fi: 'toteutuu kokonaan',
                sv: 'genomförs helt',
                value: 3,
            },
        ],
        is_visible: true,
        eos_allowed: true,
        eos_value: {
            fi: 'ei koske ryhmääni',
            sv: 'gäller inte min grupp',
            value: 0,
        },
    },
    {
        name: 'vastuut',
        order_no: 11,
        label: {
            fi: 'Vastuut',
            sv: 'Ansvar',
        },
        min_value: 1,
        max_value: 3,
        default_value: 2,
        step_count: 3,
        scale: [
            {
                fi: 'vastuita ei ole määritelty',
                sv: 'ansvaret är inte definierat',
                value: 1,
            },
            {
                fi: 'vastuut ovat jossain määrin epäselvät',
                sv: 'ansvaret är något oklart',
                value: 2,
            },
            {
                fi: 'vastuut on määritelty',
                sv: 'ansvaret är definierat',
                value: 3,
            },
        ],
        is_visible: true,
        eos_allowed: true,
        eos_value: {
            fi: 'ei koske ryhmääni',
            sv: 'gäller inte min grupp',
            value: 0,
        },
    },
];

export default kyselyData;
